# docker-compose
#
alias dc='docker-compose'
alias dcimg='docker-compose image'
alias dcexec='docker-compose exec'
alias dcrun='docker-compose run'
alias dcstop='docker-compose stop'
alias dcrm='docker-compose rm'
alias dcupd='docker-compose up -d'
alias dclog='docker-compose log'
alias dclogf='docker-compose log -f'
alias dcstart='docker-compose start'
alias dcrst='docker-compose restart'
alias dcpull='docker-compose pull'
alias dckill='docker-compose kill'
alias dcps='docker-compose ps -a'
